# Generated by Django 3.2.4 on 2021-07-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phapp', '0004_project_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
    ]
